name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v2
        with:
          xcode-version: '14.x'  # Adjust this based on your Xcode version

      - name: Install Dependencies
        run: |
          # Install CocoaPods dependencies (if applicable)
          if [ -f "Podfile" ]; then
            pod install
          fi

      - name: Build the iOS App
        run: |
          xcodebuild -workspace SignApp.xcworkspace \ # Use .xcworkspace if you have a CocoaPods setup, otherwise use .xcodeproj
                     -scheme SignApp \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     build

      - name: Run Unit Tests
        run: |
          xcodebuild test -workspace SignApp.xcworkspace \
                          -scheme SignApp \
                          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1'
